# Generated by Django 4.2.5 on 2026-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
