# Generated by Django 4.2.5 on 2026-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobid", models.IntegerField(unique=True)),
                ("jobName", models.CharField(max_length=50)),
                ("jobLocation", models.CharField(max_length=60)),
                ("jobCountry", models.CharField(max_length=60)),
                ("createDate", models.DateField(auto_now_add=True)),
                ("updateDate", models.DateField(auto_now=True)),
                ("department", models.CharField(max_length=30)),
                ("jobDescription", models.CharField(max_length=500)),
                ("requirement", models.CharField(max_length=300)),
                ("yearsOfExp", models.DecimalField(decimal_places=1, max_digits=3)),
                ("aboutDesc", models.CharField(max_length=300)),
                ("creatorName", models.CharField(max_length=50)),
                ("updatorName", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("tags", models.JSONField(default=list)),
            ],
        ),
    ]
