# Generated by Django 4.2.5 on 2026-02-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="createDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="updateDate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
